# https://taskfile.dev/usage/
version: '3'

env:
  VERSION: latest
  IMAGE: tmp_test_image
  PLATFORM: linux/amd64

dotenv: ['.env']
output: 'group'

tasks:
  default: task --list-all

  build:
    desc: "Building the docker image"
    aliases: [buildx,init]
    cmds:
      - docker buildx build -f Dockerfile -t $IMAGE:$VERSION --platform $PLATFORM .

  run:
    desc: "Building the docker image"
    cmds:
      - docker run --rm $IMAGE:$VERSION

  multiple:
    desc: "Run the task 'run' multiple times"
    cmds:
      - task: run
      - task: run
      - task: run
      - task: run
    silent: true

  print:
    desc: "Printing some string with vars"
    silent: true
    cmds:
      - "echo Variable print. Var1: $(VAR1), Var2: $(VAR2)"


# Since v3 there is a short task syntax
# https://taskfile.dev/usage/#short-task-syntax

  buildv3: docker buildx build -f Dockerfile -t $IMAGE:$VERSION --platform $PLATFORM .
